name: "Run Tests"
on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        run: npm install
      - name: Run Tests
        run: npm run test
